
  export function ToUrlPeace(name : string){
    name = name.toLowerCase()
    .replace(/  /g," ")
    .replace(/ /g,"-")
    .replace("(","-")
    .replace(")","-")
    .replace("[","-")
    .replace("]","-")
    .replace("...","")
    .replace(/á/g,"a")
    .replace(/à/g,"a")
    .replace(/ã/g,"a")
    .replace(/â/g,"a")
    .replace(/é/g,"e")
    .replace(/ê/g,"e")
    .replace(/í/g,"i")
    .replace(/ó/g,"o")
    .replace(/õ/g,"o")
    .replace(/ô/g,"o")
    .replace(/ö/g,"o")
    .replace(/ú/g,"u")
    .replace(/ü/g,"u")
    .replace(/ç/g,"c")
    .replace(/ª/g,"a")
    .replace(/º/g,"o")
    .replace(/°/g,"o")
    .replace("...","")
    .replace(/:/g,"")
    .replace(/;/g,"")
    .replace(/%/g,"")
    .replace(/'/g,"")
    .replace(/’/g,"")
    .replace(/‘/g,"")
    .replace(".","")
    .replace("!","")
    .replace("?","")
    .replace(/&/g,"")
    .replace(/–/g,"-")
    .replace(/---/g,"-")
    .replace(/--/g,"-")
    .replace(/š/g,"")
    .replace(/ž/g,"")
    .replace(/~/g,"")
    .replace(/œ/g,"o")
    .replace("...","")
    .replace("…","")
    .replace("#","");
    return name;
  }
